spring:
  application:
    name: be

  datasource:
    url: jdbc:mysql://localhost:3306/aladdinDB?serverTimezone=UTC&characterEncoding=UTF-8 # MySQL ???? ?? ? ??? ?????? ??
    username: test # MySQL ???? ?? ? ??? ??? ??
    password: 1234 # MySQL ???? ?? ? ??? ??? ?? ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # ?????? ?? ? ??? ?? ?? (?? ????? ?? ??)
    show-sql: true # SQL ?? ?? (?? ????? ?? ??)
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? (?? ????? ?? ??)
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL ??? ?? Dialect ??

