spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true # For contextLoads error
