spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venus
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
