aladin:
  key: ttbolivia09291715001
tmdb:
  key: f22124aadf1db63b236d4c779fbd97d6
  accessToken: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMjIxMjRhYWRmMWRiNjNiMjM2ZDRjNzc5ZmJkOTdkNiIsIm5iZiI6MTczNDM5ODIwNy40NjMsInN1YiI6IjY3NjBkMGZmNjY5Njc1YzVhZmJhZmU2MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.HCKuqu5YS0HNgUlDlZaFR2l5IN5UwmjdRby9Icotld4