name: be-ci
on:
  pull_request:
    branches:
      - dev-be

env:
  ROOT_PATH: ${{ github.workspace }}/be
  MAIN_RESOURCE_PATH: ${{ github.workspace }}/be/src/main/resources
  TEST_RESOURCE_PATH: ${{ github.workspace }}/be/src/test/resources
#  COVERALLS_PATH: ${{ github.workspace }}/be/build/reports/jacoco/test/jacocoTestReport.xml

jobs:
  be-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리를 체크아웃한다
        uses: actions/checkout@v4
      - name: 자바를 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: 설정파일을 추가한다
        run: |
          cd ${{ env.MAIN_RESOURCE_PATH }}
          echo "${{ secrets.APPLICATION_AWS_YML }}" > application-aws.yml
      #          echo "${{ secrets.APPLICATION_JWT_YML }}" > application-jwt.yml
      #          echo "${{ secrets.APPLICATION_OAUTH_YML }}" > application-oauth.yml
      - name: 어플리케이션을 빌드한다
        run: |
          chmod +x gradlew
          ./gradlew build
        working-directory: ${{ env.ROOT_PATH }}
